version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7.29
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mybitcoin
      MYSQL_USER: mybitcoin
      MYSQL_PASSWORD: qKjdWwnaCS8dERtn
      MYSQL_ROOT_PASSWORD: qKjdWwnaCS8dERtn
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel
    command: sh -c "chown -R www-data:www-data ./ && php-fpm"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel
    command: bash -c "cp .env.production .env && composer install --no-dev --prefer-dist --optimize-autoloader && composer clear-cache && php artisan config:cache --ansi"

  npm:
    image: node:12.16.2
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - artisan
    entrypoint: ['npm']
    command: run deploy

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - composer
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
    restart: on-failure
    command: deploy
